"""Configuração central de categorias e palavras-chave."""

CATEGORIAS: dict[str, list[str]] = {
    "Alimentação": [
        "ifood",
        "restaurante",
        "lanchonete",
        "pizza",
        "burger",
        "bar",
        "mercado",
        "supermercado",
        "carrefour",
        "extra",
        "assai",
        "pao de acucar",
        "bom lugar",
    ],
    "Saúde": [
        "farmacia",
        "drogaria",
        "hospital",
        "clinica",
        "farma",
        "laboratorio",
        "exame",
        "consulta",
    ],
    "Transporte/Auto": [
        "uber",
        "99",
        "taxi",
        "posto",
        "combustivel",
        "gasolina",
        "shell",
        "ipiranga",
        "sem parar",
        "carro",
        "auto",
        "oficina",
        "pneu",
        "pedagio",
        "estacionamento",
    ],
    "Compras/Lojas": [
        "amazon",
        "mercadolivre",
        "shopee",
        "magalu",
        "loja",
        "shopping",
        "roupa",
        "calcado",
        "vestuario",
    ],
    "Serviços/Telecom": [
        "internet",
        "net",
        "vivo",
        "tim",
        "claro",
        "oi",
        "telefonia",
        "telefone",
        "catnet",
        "fibra",
        "wifi",
    ],
    "Serviços/Streaming": [
        "netflix",
        "spotify",
        "amazon prime",
        "prime video",
        "youtube",
        "hbo",
        "max",
        "disney",
        "globoplay",
        "streaming",
    ],
    "Educação": [
        "curso",
        "escola",
        "faculdade",
        "universidade",
        "livro",
        "apostila",
        "mensalidade",
        "aula",
    ],
    "Lazer": [
        "cinema",
        "viagem",
        "parque",
        "show",
        "ingresso",
        "passeio",
        "familia",
        "lazer",
        "entretenimento",
    ],
    "Outros Serviços": [
        "condominio",
        "iptu",
        "luz",
        "energia",
        "agua",
        "aluguel",
        "seguro",
        "prestacao",
        "financiamento",
        "taxa",
        "manutencao",
        "limpeza",
        "servico",
        "apm",
        "ap",
    ],
}
